[package]
name = "lunarrelay"
authors = ["Nathan Perry <np@nathanperry.dev>"]
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
smol = "1.2"
async-compat = "0.2"
async-broadcast = "0.4"
async-trait = "0.1"
async-std = "1.11"
futures = "0.3"
tokio-serial = "5.4"

serde = { version = "1.0.136", features = ["derive"] }
serde_repr = "0.1"
serde_json = "1.0"
brotli = "3.3"
postcard = { version = "0.7", features = ["alloc", "use-std"] }

eyre = "0.6"
lazy_static = "1.4"
cfg-if = "1.0"
structopt = "0.3"
failsafe = "1.1"
either = "1.6"
fnv = "1.0"

signal-hook = "0.3"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-unwrap = "0.9"
tracing-log = "0.1"

[build-dependencies]
vergen = "6.0"
anyhow = "1.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
