[package]
name = "lunarrelay"
author = "Nathan Perry <np@nathanperry.dev>"
version = "0.1.0"
edition = "2021"

[dependencies]
smol = "1.2"
async-compat = "0.2"
futures = "0.3"

anyhow = "1.0"
lazy_static = "1.4.0"