[package]
name = "lunarrelay"
authors = ["Nathan Perry <np@nathanperry.dev>"]
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
smol = "1.2"
async-compat = "0.2"
async-broadcast = "0.4"
async-trait = "0.1"
async-std = "1.11"
futures = "0.3"
tokio-serial = "5.4"
stream-cancel = "0.8"

serde = { version = "1.0.136", features = ["derive"] }
serde_repr = "0.1"
serde_json = "1.0"
brotli = "3.3"
packed_struct = { version = "0.10", features = ["use_serde"] }
crc = "3.0"
byteorder = "1.4"
smallvec = "1.8"
hex = "0.4"
cobs = { version = "0.1", optional = true }

eyre = "0.6"
either = "1.6"
backoff = { version = "0.4", features = ["futures", "async-std"] }

lazy_static = "1.4"
cfg-if = "1.0"
derive_more = "0.99"
structopt = "0.3"
fnv = "1.0"
chrono = "0.4"
dashmap = "5.3"
tap = "1.0"
once_cell = "1.12"

num-traits = "0.2"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-unwrap = "0.9"
tracing-log = "0.1"

paste = "1.0"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3"
libloading = "0.7"

[target.'cfg(windows)'.dependencies]
ctrlc = "3.2"

[features]
default = ["serial_cobs"]
serial_cobs = ["cobs"]

[dev-dependencies]
proptest = "1.0"

[build-dependencies]
vergen = "6.0"
anyhow = "1.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
