[package]
name = "lunarrelay"
authors = ["Nathan Perry <np@nathanperry.dev>"]
version = "0.1.0"
edition = "2021"

[dependencies]
smol = "1.2"
async-compat = "0.2"
async-broadcast = "0.4"
async-trait = "0.1"
async-std = "1.11"
futures = "0.3"

serde = { version = "1.0.136", features = ["derive"] }
rmp-serde = "1.0.0"

anyhow = "1.0"
lazy_static = "1.4"

signal-hook = "0.3"

tracing = { version = "0.1", features = ["log", "log-always"] }
fern = { version = "0.6", features = ["colored"] }
log = "0.4"
