[toolchain]
channel = "nightly-2022-03-29"
components = [ "rustfmt", "clippy", "rust-src", "rust-docs" ]
profile = "minimal"
targets = [ "x86_64-pc-windows-msvc", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu" ]
