[package]
name = "antrelay-tracing"
authors = ["Nathan Perry <np@nathanperry.dev>"]
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
derive_more = "0.99"
serde = { version = "1.0", features = ["derive"] }
actix = "0.13"
actix-broker = "0.4"
